name: Build & Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run package -- --publish never
      - name: Set custom icon on DMG file
        run: |
          brew install fileicon
          fileicon set dist/bella-md-*.dmg build/icon.png
      - uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: dist/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run package:win -- --publish never
      - uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*-setup.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run package:linux -- --publish never
      - uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: dist/*.AppImage
